apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-ide-controller-rb
  namespace: cloud-ide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-ide-controller-role
subjects:
- kind: ServiceAccount
  name: cloud-ide-controller-sa
  namespace: cloud-ide-apps
