apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-ide-controller-role
  namespace: cloud-ide
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - create
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
