server:
  host: "0.0.0.0"
  port: 8088
  name: "unknown"
  mode: "Release"

mysql:
  dataSourceName: "root:123456@@@(cloud-ide-mysql-svc:3306)/cloudcode?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20
  maxIdleConns: 10

logger:
  level: "DEBUG"
  filePath: "./log_file"
  fileName: "log.log"
  maxFileSize: 1073741824
  toFile: false

redis:
  addr: "cloud-ide-redis-svc:6379"
  poolSize: 10
  minIdleConns: 5
  password: ""
  db: 0

grpc:
  addr: "cloud-ide-operator-svc:6387"

email:
  host: "smtp.qq.com"
  port: 25
  senderEmail: ""
  authCode: ""
