apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-ide-operator-rb
  namespace: cloud-ide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-ide-operator-role
subjects:
- kind: ServiceAccount
  name: cloud-ide-operator-sa
  namespace: cloud-ide-apps
